---
- name: Configurar NGINX como proxy para dos rutas
  hosts: localhost
  gather_facts: false
  vars:
    project_root: "{{ playbook_dir }}/.."
    nginx_conf_host: "{{ project_root }}/host_volumes/nginx_conf"
    nginx_container: "nginx_proxy"

  tasks:
    - name: Crear las carpetas
      ansible.builtin.file:
        path: "{{item}}"
        state: directory
        mode: "0755"
      loop:
        - "{{nginx_conf_host}}"
        - "{{web_conf_host}}"

    - name: Copiar la configuracion de NGINX
      ansible.builtin.copy:
        src: "templates/nginx.conf"
        dest: "{{nginx_conf_host}}/default.conf"
        mode: "0644"

    - name: Intentar recargar NGINX
      ansible.builtin.command: >
        docker exec {{nginx_container}} nginx -s reload
      register: reload_result
      changed_when: reload_result.rc == 0
      failed_when: false

    - name: Reiniciar contenedor por si falla la recarga
      ansible.builtin.command: >
        docker restart {{nginx_container}}
      when: reload_result.rc != 0